- platform: workday
  country: Norway

- platform: bayesian
  prior: 0.9
  name: Tuva Presence
  probability_threshold: 0.9
  observations:
  - entity_id: 'device_tracker.tuva'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.satan'
    prob_given_true: 0.9
    prob_given_false: 0.9
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.tuva_gps'
    prob_given_true: 0.2
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'

- platform: bayesian
  prior: 0.9
  name: Trym Presence
  probability_threshold: 0.9
  observations:
  - entity_id: 'device_tracker.trym'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.trymmoblue'
    prob_given_true: 0.9
    prob_given_false: 0.9
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.trym_gps'
    prob_given_true: 0.2
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'

- platform: bayesian
  prior: 0.9
  name: Tiril Presence
  probability_threshold: 0.9
  observations:
  - entity_id: 'device_tracker.tiril'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.pippin'
    prob_given_true: 0.9
    prob_given_false: 0.9
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.tiril_gps'
    prob_given_true: 0.2
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'

- platform: bayesian
  prior: 0.9
  name: Jeanette Presence
  probability_threshold: 0.9
  observations:
  - entity_id: 'device_tracker.jeanette'
    prob_given_true: 1
    prob_given_false: 0
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.jeanettofon'
    prob_given_true: 1
    prob_given_false: 0
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.jeanette_gps'
    prob_given_true: 0.85
    prob_given_false: 0.05
    platform: 'state'
    to_state: 'home'

- platform: bayesian
  prior: 0.9
  name: Tarald Presence
  probability_threshold: 0.9
  observations:
  - entity_id: 'device_tracker.tarald'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.das_ifon'
    prob_given_true: 0.9
    prob_given_false: 0.9
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.tarald_gps'
    prob_given_true: 0.2
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'
